name: Build Axyl's Artix-based ISO

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    container:
      image: angelofallaria/artix-base
      options: --privileged

    steps:
      - name: Update packages
        run: pacman -Syu --noconfirm --needed artools iso-profiles archlinux-keyring archlinux-mirrorlist

      - uses: actions/checkout@v3

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV

      - name: Setup symlinks for the build config
        run: |
          mkdir ~/.config
          ln -sf "$(pwd)/artixiso/artools-workspace" ~/
          ln -sf "$(pwd)/config/artools" ~/.config/

      - name: Cache pacman packages
        uses: actions/cache@v3
        with:
          path: /var/cache/pacman/pkg/
          key: artix-packages

      - name: Build ISO
        working-directory: ./artixiso/artools-workspace/iso-profiles/
        run: ./build.sh

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: axyl-artix-iso
          path: /root/artools-workspace/iso/*
